In [2]:
import pandas as pd

In [5]:

df = pd.read_excel("https://github.com/chris1610/pbpython/blob/master/data/sample-salesv3.xlsx?raw=True")
df["date"] = pd.to_datetime(df['date'])
df.head()

,account number,name,sku,quantity,unit price,ext price,date
0,740150,Barton LLC,B1-20000,39,86.69,3380.91,2014-01-01 07:21:51
1,714466,Trantow-Barrows,S2-77896,-1,63.16,-63.16,2014-01-01 10:00:47
2,218895,Kulas Inc,B1-69924,23,90.70,2086.10,2014-01-01 13:24:58
3,307599,"Kassulke, Ondricka and Metz",S1-65481,41,21.05,863.05,2014-01-01 15:05:22
4,412290,Jerde-Hilpert,S2-34077,6,83.21,499.26,2014-01-01 23:26:55

In [6]:
df.set_index('date').resample('M')["ext price"].sum()

/var/folders/zn/8l1qxk_s2z12z2dtb7lgbsdm0000gn/T/ipykernel_5020/3005269738.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.set_index('date').resample('M')["ext price"].sum()

date
2014-01-31    185361.66
2014-02-28    146211.62
2014-03-31    203921.38
2014-04-30    174574.11
2014-05-31    165418.55
2014-06-30    174089.33
2014-07-31    191662.11
2014-08-31    153778.59
2014-09-30    168443.17
2014-10-31    171495.32
2014-11-30    119961.22
2014-12-31    163867.26
Freq: ME, Name: ext price, dtype: float64

In [1]:
df.set_index('date').groupby('name')["ext price"].resample("M").sum()

NameError: name 'df' is not defined

In [12]:
# Improves agg() function
df.set_index('date').groupby('name')["ext price"].resample("M").sum().unstack().fillna(0)

/var/folders/zn/8l1qxk_s2z12z2dtb7lgbsdm0000gn/T/ipykernel_5020/493666191.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.set_index('date').groupby('name')["ext price"].resample("M").sum().unstack().fillna(0)

date,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31
name,,,,,,,,,,,,
Barton LLC,6177.57,12218.03,3513.53,11474.20,10220.17,10463.73,6750.48,17541.46,14053.61,9351.68,4901.14,2772.90
"Cronin, Oberbrunner and Spencer",1141.75,13976.26,11691.62,3685.44,6760.11,5379.67,6020.30,5399.58,12693.74,9324.37,6021.11,7640.60
"Frami, Hills and Schmidt",5112.34,4124.53,10397.44,5036.18,4097.87,13192.19,13177.81,7803.08,8634.88,8522.44,7221.02,16249.81
"Fritsch, Russel and Anderson",15130.77,9595.35,5153.80,9302.57,11347.23,7722.40,13278.82,340.08,11078.79,10686.18,6233.08,12345.64
"Halvorson, Crona and Champlin",9997.17,7082.15,9610.91,5591.84,2284.79,3648.32,10411.53,4194.44,4947.29,5318.22,4017.19,2900.51
Herman LLC,10749.84,5831.40,6359.58,4379.21,2529.40,5566.85,10194.26,3018.32,19250.86,5271.59,5049.15,4664.54
Jerde-Hilpert,11274.33,4088.40,15254.78,7827.74,10049.22,12008.45,9106.47,8985.41,8524.98,11401.27,7128.39,6941.99
"Kassulke, Ondricka and Metz",7322.83,3061.12,10159.76,8368.10,2183.27,5928.93,6204.91,7383.14,12449.53,10127.44,8836.82,4425.22
Keeling LLC,6847.86,3383.45,17110.10,8937.57,11932.89,9798.46,13617.19,1340.90,3488.91,918.13,10310.96,13247.88
Kiehn-Spinka,8097.50,3461.12,9468.44,6261.61,6660.04,13705.59,11344.78,8825.29,7093.43,4285.04,3004.65,17401.28
Koepp Ltd,10768.33,331.40,6282.16,14358.92,19012.78,6127.13,1305.72,14101.50,5901.53,8797.80,4882.27,11791.00
Kuhn-Gusikowski,7309.54,6788.80,15896.09,8781.61,5183.04,746.74,13007.48,3934.64,6728.83,10559.77,7197.89,4959.85
Kulas Inc,15398.87,13973.65,24134.84,11030.73,11901.27,7365.56,6120.80,8929.12,12487.12,15754.28,4149.34,6106.38
Pollich LLC,1004.22,1502.43,6791.37,8557.14,13109.61,8340.95,12552.35,6158.86,4018.12,6620.16,6334.21,12357.76
Purdy-Kunde,4689.37,5545.07,4169.16,6740.85,8389.55,6126.62,10807.88,10344.62,4158.01,10499.29,2376.00,4051.79
Sanford and Sons,9544.13,4070.62,10389.18,12344.86,12627.85,7973.10,10829.87,9673.43,10685.68,1698.74,6834.04,2151.48
Stokes LLC,5809.34,10610.04,9261.05,11224.21,3681.51,19008.00,3683.96,4826.04,5594.23,5312.47,6158.81,6366.26
Trantow-Barrows,14328.26,11170.76,9855.59,5567.19,5713.71,13775.80,11987.34,17251.65,6992.48,10064.27,6550.10,10124.23
White-Trantow,13703.77,11783.98,8583.05,19009.20,5877.29,14791.32,10242.62,12287.21,5315.16,19896.85,9544.61,4806.93
Will LLC,20953.87,13613.06,9838.93,6094.94,11856.95,2419.52,11017.54,1439.82,4345.99,7085.33,3210.44,12561.21

In [13]:
df.agg({'ext price': ['sum', 'mean'], 'quantity': ['sum', 'mean'], 'unit price': ['mean']})

         ext price      quantity  unit price
sum   2.018784e+06  36463.000000         NaN
mean  1.345856e+03     24.308667   55.007527

In [ ]:
# Custom aggregation function with a name
get_max = lambda x: x.value_counts(dropna=False).index[0]
get_max.__name__ = "most frequent"

In [17]:
import collections
f = collections.OrderedDict([('ext price', ['sum', 'mean']), ('quantity', ['sum', 'mean']), ('sku', [get_max])])
df.agg(f)

                  ext price      quantity       sku
sum            2.018784e+06  36463.000000       NaN
mean           1.345856e+03     24.308667       NaN
most frequent           NaN           NaN  S2-77896

In [ ]:
https://pbpython.com/market-basket-analysis.html